### ISSUE TITLE
MacOS Platform: cannot compile on MacOs Catalina (10.15.6), memset_pattern4() prototype

### ISSUE THREAD

**Issue by JesperGravgaard** [lgblgblgb/xemu#144]
**Describe the bug**
I have a newly installed MacBook with Catalina 10.15.6.

Following the instructions in https://github.com/lgblgblgb/xemu/blob/master/README.md results in an error during compile.

**Used version of the project**

The problem occurs on the master branch of the repository. Current commit is 0d43fb97c26349a7cc820356f9113db86a95fc7d.

**To Reproduce**
1. Install MacOs Catalina 10.15.6
2. Install homebrew
3. brew update
4. brew install sdl2 wget git
5. git clone git@github.com:lgblgblgb/xemu.git
5. cd xemu
6. make

**Expected behavior**
Successful compilation.

**Actual behavior**

The following error occurs during the configuration-part of the compilation
```
Analyzing compilation target: SYSTEM=osx IS_UNIX=Y IS_WIN=N IS_WIN32=N IS_WIN64=N IS_OSX=Y IS_LINUX=N IS_HTML=N
Checking sdl2-config script as "sdl2-config" ... seems to work
Detected SDL2 version ... 2.0.12
Trying to compile something against SDL2 ... ERROR
*** Error message ***
In file included from build/objs/configure--script--native--test.c:2:
In file included from /usr/local/include/SDL2/SDL.h:32:
In file included from /usr/local/include/SDL2/SDL_main.h:25:
/usr/local/include/SDL2/SDL_stdinc.h:426:5: error: implicit declaration of function 'memset_pattern4' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    memset_pattern4(dst, &val, dwords * 4);
    ^
1 error generated.
*** xemu-configure has FAILED ***
make[1]: *** [../../build/configure/config-native.make] Error 1
make: *** [all] Error 1
```

**Computer/Device (please complete the following information):**
 - OS and its version:  MacOs Catalina 10.15.6

**Comment by lgblgblgb** [comment]
Thanks for the report. This bug - I believe - is fixed already (by me) just not in the master branch (or the hmw which is based more on an older forked dev branch). Though I was not aware of this as the solution (instead I simply defined the prototype myself, which is indeed ugly):

 #define _XOPEN_SOURCE 100

**Comment by lgblgblgb** [comment]
Please have a look on #145 on the comments. Do you have any better suggestion, opinion etc? I would say it's already solved by me in dev branch a longer time ago, but it's true, there can be better solution, and you seems to have better understanding on Mac maybe (at least HAVING one ... unlike me) so I'm open for suggestions. But if it's only about making it compile nicely and the fix in dev is enough for that ... THANKS!

**Comment by lgblgblgb** [comment]
OK, since no further comments, I close this.
