### PR TITLE
Fix #144 MacOs compile problem

### LINKED ISSUE #144: MacOS Platform: cannot compile on MacOs Catalina (10.15.6), memset_pattern4() prototype
**Describe the bug**
I have a newly installed MacBook with Catalina 10.15.6.

Following the instructions in https://github.com/lgblgblgb/xemu/blob/master/README.md results in an error during compile.

**Used version of the project**

The problem occurs on the master branch of the repository. Current commit is 0d43fb97c26349a7cc820356f9113db86a95fc7d.

**To Reproduce**
1. Install MacOs Catalina 10.15.6
2. Install homebrew
3. brew update
4. brew install sdl2 wget git
5. git clone git@github.com:lgblgblgb/xemu.git
5. cd xemu
6. make

**Expected behavior**
Successful compilation.

**Actual behavior**

The following error occurs during the configuration-part of the compilation
```
Analyzing compilation target: SYSTEM=osx IS_UNIX=Y IS_WIN=N IS_WIN32=N IS_WIN64=N IS_OSX=Y IS_LINUX=N IS_HTML=N
Checking sdl2-config script as "sdl2-config" ... seems to work
Detected SDL2 version ... 2.0.12
Trying to compile something against SDL2 ... ERROR
*** Error message ***
In file included from build/objs/configure--script--native--test.c:2:
In file included from /usr/local/include/SDL2/SDL.h:32:
In file included from /usr/local/include/SDL2/SDL_main.h:25:
/usr/local/include/SDL2/SDL_stdinc.h:426:5: error: implicit declaration of function 'memset_pattern4' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    memset_pattern4(dst, &val, dwords * 4);
    ^
1 error generated.
*** xemu-configure has FAILED ***
make[1]: *** [../../build/configure/config-native.make] Error 1
make: *** [all] Error 1
```

**Computer/Device (please complete the following information):**
 - OS and its version:  MacOs Catalina 10.15.6

### PR DESCRIPTION
**Pull request by JesperGravgaard**
I have found a solution for getting a successful on my newly installed MacOs - by setting the _XOPEN_SOURCE version to 100, which avoids the problem.

See Issue #144 for a description of the error.

### CODE REVIEW

**Comment by lgblgblgb** [comment]
I'm wondering if this is different in result or not:

    #if defined(XEMU_ARCH_UNIX) && !defined(_XOPEN_SOURCE)
    #       define  _XOPEN_SOURCE   700
    #endif

Note, that XEMU_ARCH_UNIX is defined at this point for MacOS. This is already in Xemu. However what you suggest:

    #define _XOPEN_SOURCE 100

No idea about '100' and its meaning, the sources I could find mention these only:

    500 - X/Open 5, incorporating POSIX 1995
    600 - X/Open 6, incorporating POSIX 2004
    700 - X/Open 7, incorporating POSIX 2008

Also, as far as I can remember, I tried setting _XOPEN_SOURCE but it does not helped so I ended with defining the prototype for memset_pattern4() as my own, which is indeed an ugly solution.

**Comment by JesperGravgaard** [comment]
I used the value 100 is used to prevent the value 700. I tested all 3 values 500, 600, 700 and the all resulted in a fatal memset_pattern4() problem on my MacBook with a new and clean install of Catalina where I have only installed <5 programs before trying to compile Xemu following your instructions.

On my iMac which has been upgraded to Catalina from previous MacOs versions and has a ton of installed software the memset_pattern4() is not fatal. Probably some other development packages installed using brew prevents the problem from being fatal - but I do not know enough about how X/Open to know where to start :)

Creating a prototype for memset_pattern4() would probably also be a good solution to the problem. 

If you prefer that to the _XOPEN_SOURCE 100 then I have no objections. I will test how that works on my MacBook.

**Comment by JesperGravgaard** [comment]
I just tested this approach.

Adding  `#include <string.h>`, which declares  memset_pattern4() to arch-sys.h works perfectly fine and removes the need for _XOPEN_SOURCE 100.

Would you like me to update the pull request / make a new one with that change instead?

**Comment by lgblgblgb** [comment]
This is more and more cryptic for me. Since I've already tried string.h of course, see arch-sys.h:

    #ifdef XEMU_ARCH_OSX
            // MacOS and/or SDL bug: even if this prototype is in string.h system header in MacOS,
            // somehow it does not work even if string.h _IS_ included. So I have to create my
            // own prototype for this function here :-O For the prototype, we also need the stddef.h
            // though, for the "size_t".
    #       include <stddef.h>
            void memset_pattern4(void *__b, const void *__pattern4, size_t __len);
    #endif

I've commented here, that including string.h did not solved the problem for me. At least with the MacOS version I have on Travis for Mac builds. As I've said, unfortunately, I have no (and had no) Mac, so it took huge amount of time for me to construct scripts for testing and submit to Travis to be able to check the output :-/ As far as I can remember, I even made Travis to display string.h and it has interesting "atleast" like construct for memset_pattern4() - sorry I forgot what was that exactly - which seems to be kind of odd custom attributes or such. However I couldn't find out what does needs to work, since according to my theory the only way including string.h and still does not have the prototype is about those "stuffs" (if you have Mac - I assume you have - please see string.h). Yes, the arch-sys.h now does not include string.h now, but that's because I've tried that and didn't helped to I dropped the ineffective extra header include when it does not solve the problem (for me, at least!) at all.

**Comment by lgblgblgb** [comment]
Oh, and one important thing! Please see arch-sys.h in my dev branch, the fragment I've quoted from is not in master yet, but **in dev**! So you should check dev branch, which will be merged into master at some point. So maybe this problem (compilation on MacOS) is already solved by me (sorry that I only realizes it) in the dev branch. That's another question though - indeed - how "nice" (so: bad ...) this workaround is, to define the prototype myself. But as I've said, I also tried to include string.h and it didn't worked for me, at least not with the MacOS version Travis has (interestingly there it just causes warnings but it does not cause the compilation to fail, but still it was very annoying).

**Comment by lgblgblgb** [comment]
OK, since no further comments, I close this.
